---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

### Gene Expression Weights

Schizophrenia results [link](SCZ_results.html).

Atrial Fibrillation - Heart Atrial Appendage Results [link](Atrial_Fibrillation_Heart_Atrial_Appendage.html).

Atrial Fibrillation - Heart Left Ventricle Results [link](Atrial_Fibrillation_Heart_Left_Ventricle.html).

T2D - Liver Results
[link](T2D_Liver.html).

T2D - Pancreas Results
[link](T2D_Pancreas.html).

T2D - Adipose Visceral Omentum
[link](T2D_Adipose_Visceral_Omentum.html).

T2D - Adipose Subcutaneous
[link](T2D_Adipose_Subcutaneous.html).

BMI - Brain Cortex
[link](BMI_Brain_Cortex.html).

BMI - Brain Spinal cord cervical c-1
[link](BMI_Brain_Spinal_cord_cervical_c-1.html).

BMI - Brain Substantia nigra
[link](BMI_Brain_Substantia_nigra.html).

BMI - Brain Putamen basal ganglia
[link](BMI_Brain_Putamen_basal_ganglia.html).

BMI - Brain Nucleus accumbens basal ganglia
[link](BMI_Brain_Nucleus_accumbens_basal_ganglia.html).

BMI - Brain Hypothalamus
[link](BMI_Brain_Hypothalamus.html).

BMI - Brain Hippocampus
[link](BMI_Brain_Hippocampus.html).

BMI - Brain Frontal Cortex BA9
[link](BMI_Brain_Frontal_Cortex_BA9.html).

BMI - Brain Cerebellum
[link](BMI_Brain_Cerebellum.html).

BMI - Brain Cerebellar Hemisphere
[link](BMI_Brain_Cerebellar_Hemisphere.html).

BMI - Brain Caudate basal ganglia
[link](BMI_Brain_Caudate_basal_ganglia.html).

BMI - Brain Anterior cingulate cortex BA24
[link](BMI_Brain_Anterior_cingulate_cortex_BA24.html).

BMI - Brain Amygdala
[link](BMI_Brain_Amygdala.html).

Autism - Brain Cortex
[link](Autism_Brain_Cortex.html).

Autism - Brain Spinal cord cervical c-1
[link](Autism_Brain_Spinal_cord_cervical_c-1.html).

Autism - Brain Substantia nigra
[link](Autism_Brain_Substantia_nigra.html).

Autism - Brain Putamen basal ganglia
[link](Autism_Brain_Putamen_basal_ganglia.html).

Autism - Brain Nucleus accumbens basal ganglia
[link](Autism_Brain_Nucleus_accumbens_basal_ganglia.html).

Autism - Brain Hypothalamus
[link](Autism_Brain_Hypothalamus.html).

Autism - Brain Hippocampus
[link](Autism_Brain_Hippocampus.html).

Autism - Brain Frontal Cortex BA9
[link](Autism_Brain_Frontal_Cortex_BA9.html).

Autism - Brain Cerebellum
[link](Autism_Brain_Cerebellum.html).

Autism - Brain Cerebellar Hemisphere
[link](Autism_Brain_Cerebellar_Hemisphere.html).

Autism - Brain Caudate basal ganglia
[link](Autism_Brain_Caudate_basal_ganglia.html).

Autism - Brain Anterior cingulate cortex BA24
[link](Autism_Brain_Anterior_cingulate_cortex_BA24.html).

Autism - Brain Amygdala
[link](Autism_Brain_Amygdala.html).

SCZ - Brain Cortex
[link](SCZ_Brain_Cortex.html).

SCZ - Brain Spinal cord cervical c-1
[link](SCZ_Brain_Spinal_cord_cervical_c-1.html).

SCZ - Brain Substantia nigra
[link](SCZ_Brain_Substantia_nigra.html).

SCZ - Brain Putamen basal ganglia
[link](SCZ_Brain_Putamen_basal_ganglia.html).

SCZ - Brain Nucleus accumbens basal ganglia
[link](SCZ_Brain_Nucleus_accumbens_basal_ganglia.html).

SCZ - Brain Hypothalamus
[link](SCZ_Brain_Hypothalamus.html).

SCZ - Brain Hippocampus
[link](SCZ_Brain_Hippocampus.html).

SCZ - Brain Frontal Cortex BA9
[link](SCZ_Brain_Frontal_Cortex_BA9.html).

SCZ - Brain Cerebellum
[link](SCZ_Brain_Cerebellum.html).

SCZ - Brain Cerebellar Hemisphere
[link](SCZ_Brain_Cerebellar_Hemisphere.html).

SCZ - Brain Caudate basal ganglia
[link](SCZ_Brain_Caudate_basal_ganglia.html).

SCZ - Brain Anterior cingulate cortex BA24
[link](SCZ_Brain_Anterior_cingulate_cortex_BA24.html).

SCZ - Brain Amygdala
[link](SCZ_Brain_Amygdala.html).

### Alternative Splicing Weights

BMI - Brain Cortex
[link](BMI_Brain_Cortex_S.html).

BMI - Brain Spinal cord cervical c-1
[link](BMI_Brain_Spinal_cord_cervical_c-1_S.html).

BMI - Brain Substantia nigra
[link](BMI_Brain_Substantia_nigra_S.html).

BMI - Brain Putamen basal ganglia
[link](BMI_Brain_Putamen_basal_ganglia_S.html).

BMI - Brain Nucleus accumbens basal ganglia
[link](BMI_Brain_Nucleus_accumbens_basal_ganglia_S.html).

BMI - Brain Hypothalamus
[link](BMI_Brain_Hypothalamus_S.html).

BMI - Brain Hippocampus
[link](BMI_Brain_Hippocampus_S.html).

BMI - Brain Frontal Cortex BA9
[link](BMI_Brain_Frontal_Cortex_BA9_S.html).

BMI - Brain Cerebellum
[link](BMI_Brain_Cerebellum_S.html).

BMI - Brain Cerebellar Hemisphere
[link](BMI_Brain_Cerebellar_Hemisphere_S.html).

BMI - Brain Caudate basal ganglia
[link](BMI_Brain_Caudate_basal_ganglia_S.html).

BMI - Brain Anterior cingulate cortex BA24
[link](BMI_Brain_Anterior_cingulate_cortex_BA24_S.html).

BMI - Brain Amygdala
[link](BMI_Brain_Amygdala_S.html).