---
title: "SCZ - Annotation Analysis"
author: "sheng Qian"
date: "2022-4-11"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r, echo=FALSE}
get_E_S <- function(tissue){
  S_path <- paste0("/project2/xinhe/shengqian/cTWAS/cTWAS_analysis/data/LDL_S/",tissue,"/LDL_",tissue)
  E_path <- paste0("/project2/xinhe/shengqian/cTWAS/cTWAS_analysis/data/LDL/",tissue,"/LDL_",tissue)
  splicing_gene <- readRDS(paste0(S_path,"_ctwas_gene_res.RDS"))
  expression_gene <- readRDS(paste0(E_path,"_ctwas_gene_res.RDS"))
  
  return(list(splicing_gene,expression_gene))
}
```

```{r, fig.height=5, fig.width=5, echo=FALSE}
brain_tissue <- list.files("/project2/xinhe/shengqian/cTWAS/cTWAS_analysis/data/SCZ_2018_S/")
par(mfrow=c(4,4))
for(i in brain_tissue){
  results <- get_E_S(i)
  splicing_gene <- results[[1]]
  expression_gene <- results[[2]]
  expression_gene['test_id'] <- sapply(expression_gene$id, function(i){strsplit(i,"[.]")[[1]][1]})
  #print(c(length(intersect(expression_gene$test_id,splicing_gene$id)),length(intersect(expression_gene$genename,splicing_gene$genename))))
  df <- merge(expression_gene[,c("genename","susie_pip")],splicing_gene[,c("genename","susie_pip")],by = "genename")
  colnames(df) <- c("genename","Expression_PIP","Splicing_PIP")
  #print(paste0(i," : ",as.character(round(cor(df$Expression_PIP,df$Splicing_PIP),3))))
  plot(df$Expression_PIP,df$Splicing_PIP, main=as.character(round(cor(df$Expression_PIP,df$Splicing_PIP),3)),
       xlab = "Expression PIP", ylab = "Splicing PIP")
}
```

```{r, fig.height=5, fig.width=5, echo=FALSE}
brain_tissue <- list.files("/project2/xinhe/shengqian/cTWAS/cTWAS_analysis/data/SCZ_2018_S/")[1:13]
causal_expression_genes <- c()
causal_splicing_genes <- c()
par(mfrow=c(4,4))
for(i in brain_tissue){
  print(i)
  results <- get_E_S(i)
  splicing_gene <- results[[1]]
  expression_gene <- results[[2]]
  causal_expression_genes <- c(causal_expression_genes,expression_gene[expression_gene$susie_pip>0.8,]$genename)
  causal_splicing_genes <- c(causal_splicing_genes,splicing_gene[splicing_gene$susie_pip>0.8,]$genename)
}

causal_expression_genes <- unique(causal_expression_genes)
causal_splicing_genes <- unique(causal_splicing_genes)
```

```{r}
table_df <- get_E_S("Brain_Cortex")
splicing_gene <- table_df[[1]]
expression_gene <- table_df[[2]]
table_df <- merge(expression_gene[,c("genename","susie_pip")],splicing_gene[,c("genename","susie_pip")],by = "genename")
colnames(table_df) <- c("genename","Expression_PIP","Splicing_PIP")
table_df["total_PIP"] <- table_df$Expression_PIP+table_df$Splicing_PIP
plot(table_df$Expression_PIP,table_df$Splicing_PIP, main=paste0("Brain Cortex: ",as.character(round(cor(table_df$Expression_PIP,table_df$Splicing_PIP),3))),
       xlab = "Expression PIP", ylab = "Splicing PIP",cex=0.8)
```

```{r}
library(VennDiagram)
 
# Generate 3 sets of 200 words
set1 <- causal_expression_genes
set2 <- causal_splicing_genes
library(RColorBrewer)
myCol <- brewer.pal(3, "Pastel2")[1:2]
# Chart
venn.diagram(
  x = list(set1, set2),
  category.names = c("Expression" , "Splicing"),
  filename = '#14_venn_diagramm.png',
  output=F,
  lwd = 2,
  lty = 'blank',
  fill = myCol,
  cat.cex = 0.8
)
```

```{r}
table_df <- get_E_S("Liver")
splicing_gene <- table_df[[1]]
expression_gene <- table_df[[2]]
table_df <- merge(expression_gene[,c("genename","susie_pip")],splicing_gene[,c("genename","susie_pip")],by = "genename",all = T)
colnames(table_df) <- c("genename","Expression_PIP","Splicing_PIP")
table_df["total_PIP"] <- table_df$Expression_PIP+table_df$Splicing_PIP
plot(table_df$Expression_PIP,table_df$Splicing_PIP, main=paste0("Brain Cortex: ",as.character(round(cor(table_df$Expression_PIP,table_df$Splicing_PIP),3))),
       xlab = "Expression PIP", ylab = "Splicing PIP",cex=0.8)
```

