---
title: "SCZ - Cross Tissue Analysis"
author: "sheng Qian"
date: "2022-3-6"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r}
brain_tissue <- list.files("/project2/xinhe/shengqian/cTWAS/cTWAS_analysis/data/SCZ/")
top_genes <- c()
for(i in brain_tissue){
  df <- readRDS(paste0("/project2/xinhe/shengqian/cTWAS/cTWAS_analysis/data/SCZ/",i,"/SCZ_",i,"_ctwas_gene_res.RDS"))
  df <- df[df$susie_pip>=0.8,]
  top_genes <- c(top_genes,df$genename)
}
top_genes <- unique(top_genes)
```

```{r}
df <- matrix(-1,nrow = length(top_genes),ncol = length(brain_tissue))
colnames(df) <- brain_tissue
rownames(df) <- top_genes
for(i in colnames(df)){
  tmp_df <- readRDS(paste0("/project2/xinhe/shengqian/cTWAS/cTWAS_analysis/data/SCZ_2014_EUR/",i,"/SCZ_",i,"_ctwas_gene_res.RDS"))
  for(j in rownames(df)){
    if(j %in% tmp_df$genename){
      df[j,i] <- tmp_df[tmp_df$genename==j,"susie_pip"]
    }
  }
}

for(i in 1:13){
  colnames(df)[i] = strsplit(colnames(df)[i],"_")[[1]][2]
}
```

```{r,fig.height=15, fig.width=15,echo=FALSE}
par(mar=c(4, 7, 4, 4))
plot(as.matrix(df), axis.row=list(side=2, las=1), axis.col=list(side=1, las=1), cex.axis = 0.8, xlab='', ylab='', main='Gene vs. Tissue', col=rev(brewer.pal(8,name = "RdYlBu")))
```