---
title: "SCZ 2018 Enrichment"
author: "shengqian"
date: "2022-05-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Load gene sets

```{r, message=FALSE, results='hide', warning=FALSE}
library(gseasusie)
library(tidyverse)

genesets <- gseasusie::load_gene_sets(c('gobp','gomf','gocc','kegg'))
#genesets <- gseasusie::load_gene_sets(c('c2'))
```

## Load gene list

```{r, message=FALSE}
library(data.table)
library("AnnotationDbi")
library("org.Hs.eg.db")
data <- fread(file = "data/magma.genes.out")
data$entrez = mapIds(org.Hs.eg.db,
                    keys=data$GENE, #Column containing Ensembl gene ids
                    column="ENTREZID",
                    keytype="ENSEMBL",
                    multiVals="first")

data <- na.omit(data)
data$beta <- 1
data$se <- 1

data <- data[,c("GENE","entrez","P","beta","se","ZSTAT")]
colnames(data) <- c("ENSEMBL","ENTREZID","pvalue","beta","se","threshold.on")
data$threshold.on <- -1*data$threshold.on
```

## Gene Ontology Biological Process

```{r, message=FALSE, echo=FALSE}
db <- 'gobp' 
thresh = -2  # threshold for binarizing the data
bin.data <- gseasusie::prep_binary_data(genesets[[db]], data, thresh)

X <- bin.data$X
y <- bin.data$y

# fit logistic susie
logistic.fit <- gseasusie::fit_logistic_susie_veb_boost(X, y, L=20)

# fit linear susie
#linear.fit <- susieR::susie(X, y)

# compute odds ratios, and pvalues under hypergeometric (one-sided) and fishers exact (two-sided) tests
ora <- gseasusie::fit_ora(X, y)
```

```{r, message=FALSE, echo=FALSE}
gseasusie::enrichment_volcano(logistic.fit, ora)
```

```{r, message=FALSE, echo=FALSE}
gseasusie::interactive_table(logistic.fit, ora)
```

## Gene Ontology Molecular Function

```{r, message=FALSE, echo=FALSE}
db <- 'gomf' 
thresh = -2  # threshold for binarizing the data
bin.data <- gseasusie::prep_binary_data(genesets[[db]], data, thresh)

X <- bin.data$X
y <- bin.data$y

# fit logistic susie
logistic.fit <- gseasusie::fit_logistic_susie_veb_boost(X, y, L=20)

# compute odds ratios, and pvalues under hypergeometric (one-sided) and fishers exact (two-sided) tests
ora <- gseasusie::fit_ora(X, y)
```

```{r, message=FALSE}
gseasusie::enrichment_volcano(logistic.fit, ora)
```

```{r, message=FALSE}
gseasusie::interactive_table(logistic.fit, ora)
```

## Gene Ontology Cellular Component

```{r, message=FALSE, echo=FALSE}
db <- 'gocc' 
thresh = -2  # threshold for binarizing the data
bin.data <- gseasusie::prep_binary_data(genesets[[db]], data, thresh)

X <- bin.data$X
y <- bin.data$y

# fit logistic susie
logistic.fit <- gseasusie::fit_logistic_susie_veb_boost(X, y, L=20)

# compute odds ratios, and pvalues under hypergeometric (one-sided) and fishers exact (two-sided) tests
ora <- gseasusie::fit_ora(X, y)
```

```{r, message=FALSE}
gseasusie::enrichment_volcano(logistic.fit, ora)
```

```{r, message=FALSE}
gseasusie::interactive_table(logistic.fit, ora)
```

# KEGG

```{r, message=FALSE, echo=FALSE}
db <- 'kegg' 
thresh = -2  # threshold for binarizing the data
bin.data <- gseasusie::prep_binary_data(genesets[[db]], data, thresh)

X <- bin.data$X
y <- bin.data$y

# fit logistic susie
logistic.fit <- gseasusie::fit_logistic_susie_veb_boost(X, y, L=20)

# compute odds ratios, and pvalues under hypergeometric (one-sided) and fishers exact (two-sided) tests
ora <- gseasusie::fit_ora(X, y)
```

```{r, message=FALSE}
gseasusie::enrichment_volcano(logistic.fit, ora)
```

```{r, message=FALSE}
gseasusie::interactive_table(logistic.fit, ora)
```